version: '3'

services:
  app:
    image: jftanner/initiate
    build: .
    container_name: initiate_app
    ports:
      - 8084:8084
    environment:
      - NODE_ENV=production
      - PORT=8084
      - REDIS_URL=redis://redis:6379
      - COUCH_URL=http://couch:5984
    depends_on:
      - redis
      - couch

  redis:
    image: redis
    container_name: initiate_redis
    volumes:
      - redis-data:/data
#    ports:
#      - 127.0.0.1:6379:6379
    expose:
      - 6379

  couch:
    image: couchdb
    container_name: initiate_couch
    volumes:
      - couchdb-data:/opt/couchdb/data
      - couchdb-config:/opt/couchdb/etc
#    ports:
#      - 127.0.0.1:5984:5984
    expose:
      - 5984

volumes:
  redis-data:
  couchdb-data:
  couchdb-config:
