version: '3'

services:
  app:
    ports:
      - 8084:8084
    environment:
      - PORT=8084

  redis:
    ports: []

  couch:
    ports: []

volumes:
  redis-data:
  couchdb-data:
  couchdb-config:
